const initialPostForm = {
  title: "",
  subtitle: "",
  tag1: "",
  tag2: "",
  tag3: "",
  tag4: "",
  tag5: "",
  section1_title: "",
  section1_text: "",
  section1_image_url: "",
  section1_image_alt: "",
  section1_video: "",
  section2_title: "",
  section2_text: "",
  section2_image_url: "",
  section2_image_alt: "",
  section2_video: "",
  section3_title: "",
  section3_text: "",
  section3_image_url: "",
  section3_image_alt: "",
  section3_video: "",
  section4_title: "",
  section4_text: "",
  section4_image_url: "",
  section4_image_alt: "",
  section4_video: "",
  section5_title: "",
  section5_text: "",
  section5_image_url: "",
  section5_image_alt: "",
  section5_video: "",
};
export default initialPostForm;
